Update keep-alive.yml

diff --git a/.github/workflows/keep-alive.yml b/.github/workflows/keep-alive.yml
--- a/.github/workflows/keep-alive.yml
+++ b/.github/workflows/keep-alive.yml
@@ -11,7 +11,7 @@ jobs:
   ping:
     runs-on: ubuntu-latest
     steps:
-      - name: Ping Supabase
+      - name: Ping Coco Supabase
         run: |
           # This command requests a single row from the REST API.
           # We use 'curl' so no extra code/dependencies are needed.
@@ -23,8 +23,25 @@ jobs:
             -H "Authorization: Bearer ${{ secrets.COCOSUPABASEKEY }}")
 
           if [ "$response" -eq 200 ]; then
-            echo "Success! Supabase is awake. HTTP 200"
+            echo "Success! COCO Supabase is awake. HTTP 200"
           else
-            echo "Failed with HTTP $response"
+            echo "COCO Failed with HTTP $response"
+            exit 1
+          fi
+- name: Ping HAWT Supabase
+        run: |
+          # This command requests a single row from the REST API.
+          # We use 'curl' so no extra code/dependencies are needed.
+
+          # REPLACE 'users' WITH ANY VALID TABLE NAME IN YOUR DATABASE
+          response=$(curl -s -o /dev/null -w "%{http_code}" \
+            "${{ secrets.HAWTSUPABASEURL }}/rest/v1/faq?select=*&limit=1" \
+            -H "apikey: ${{ secrets.HAWTSUPABASEKEY }}" \
+            -H "Authorization: Bearer ${{ secrets.HAWTSUPABASEKEY }}")
+
+          if [ "$response" -eq 200 ]; then
+            echo "Success! HAWT Supabase is awake. HTTP 200"
+          else
+            echo "HAWT Failed with HTTP $response"
             exit 1
           fi
